# -*- coding: utf-8 -*-
"""ScriptDashboardIgnacioRuelas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lxx8FdO_KTGdbHysPw8-rXRAHwiHnZ3j
"""

#Initial
import pandas as pd
import streamlit as st
st.title("Welcome to The  Nebraska Cancer Specialists (NCS) Hope Foundation daschboard")
st.markdown("""

MISSION

The NCS HOPE Foundation seeks to improve the lives of individuals and families in the community who are impacted by cancer treatment.
The foundation provides financial assistance, supportive services, and other resources to oncology and hematology patients, families, and caregivers receiving care in Nebraska.

Please use the tabs to navigate the dashboard.""")


