# -*- coding: utf-8 -*-
"""ScriptDashboardIgnacioRuelas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lxx8FdO_KTGdbHysPw8-rXRAHwiHnZ3j
"""

#Initial
import pandas as pd
import streamlit as st
st.write("Please use the tabs to navigate the dashboard.")

