# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3qCx3RTvCam5LLGNnLt1KunMbJYvqJ9
"""

!pip freeze > requirements.txt